<?php
/**
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2016 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

/**
 * List of enabled modules for this application.
 *
 * This should be an array of module namespaces used in the application.
 *
 * File generated by vendor/bin/apigility-upgrade-to-1.5.
 */
return [
    'Zend\\Cache',
    'Zend\\Db',
    'Zend\\Filter',
    'Zend\\Hydrator',
    'Zend\\InputFilter',
    'Zend\\I18n',
    'Zend\\Log',
    'Zend\\Mvc\\I18n',
    'Zend\\Paginator',
    'Zend\\Router',
    'Zend\\Validator',
    'Zend\\InputFilter',
    'Zend\\Paginator',
    'Zend\\Hydrator',
    'Zend\\Filter',
    'Zend\\ServiceManager\\Di',
    'Zend\\Log',
    'Zend\\Db',
    'Zend\\Router',
    'Zend\\Validator',
    'ZF\\Versioning',
    'ZF\\ApiProblem',
    'ZF\\ContentNegotiation',
    'ZF\\Rpc',
    'ZF\\MvcAuth',
    'ZF\\Hal',
    'ZF\\Rest',
    'ZF\\ContentValidation',
    'ZF\\Apigility',
    'Application',
];
